name: dovuihainao_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  share: ^0.6.5+4
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  cached_network_image:
  flutter_icons:
  toast:
  get:

  #  Network
  dio:
  connectivity: ^0.4.9+5

  #Admob, analytics
#  firebase_admob: ^0.10.1
#  firebase_analytics: ^6.3.0

  #  BloC
  #  equatable: ^1.2.4
  #  flutter_bloc: ^6.0.5

  #  Sqlite - Local prefrences
  #  moor: ^3.3.1
  shared_preferences: ^0.5.10
  rx_shared_preferences: ^1.3.1

  #Other
  flutter_launcher_icons: ^0.8.1
  url_launcher: ^5.7.10
  permission_handler: ^5.0.1+1
  audioplayers: ^0.17.0
  in_app_review: ^1.0.4
  image_gallery_saver: ^1.6.7
  screenshot: ^0.2.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/langs/
    - assets/sound/
    - assets/images/
    - assets/images/background/

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim_regular.ttf
    - family: Sunshiney
      fonts:
        - asset: assets/fonts/Sunshiney_regular.ttf
#    - family: Montserrat
#      fonts:
#        - asset: assets/fonts/Montserrat-MediumItalic.ttf
#          weight: 400
#        - asset: assets/fonts/Montserrat-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Montserrat-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Montserrat-SemiBold.ttf
#          weight: 600
